### ISSUE TITLE
lotus运行时错误

### ISSUE THREAD

**Issue by jinxinslim** [filestar-project/lotus#39]
lotus 版本 1.5.0  linux_amd_64
go 版本 1.15.12
运行命令  lotus daemon
错误日志
```shell
2021-09-22T15:22:50.633+0800    ^[[34mINFO^[[0m badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s

2021-09-22T15:22:50.633+0800    ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 0

2021-09-22T15:22:50.633+0800    ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1178      Replay took: 3.287µs

2021-09-22T15:22:50.650+0800    ^[[34mINFO^[[0m badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s

2021-09-22T15:22:50.651+0800    ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 0

2021-09-22T15:22:50.651+0800    ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1178      Replay took: 3.04µs

2021-09-22T15:22:50.651+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:125     opening log     {"file": "/root/.lotus/kvlog/metadata/1632295088.log.cbor"}
2021-09-22T15:22:50.651+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:182     compacting log  {"current": "/root/.lotus/kvlog/metadata/1632295088.log.cbor", "openCount": 4, "baseValues": 7, "logValues": 15, "truncated": false}
2021-09-22T15:22:50.651+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:104     creating log    {"file": "/root/.lotus/kvlog/metadata/1632295370.log.cbor"}
2021-09-22T15:22:50.652+0800    ^[[34mINFO^[[0m backupds        backupds/datastore.go:75        Starting datastore backup
2021-09-22T15:22:50.652+0800    ^[[34mINFO^[[0m backupds        backupds/datastore.go:130       Datastore backup done
2021-09-22T15:22:50.751+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:117     log opened      {"file": "/root/.lotus/kvlog/metadata/1632295370.log.cbor"}
2021-09-22T15:22:50.751+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:192     compacted log created, cleaning up old  {"old": "/root/.lotus/kvlog/metadata/1632295088.log.cbor", "new": "1632295370.log.cbor"}
2021-09-22T15:22:50.751+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:194     compacted log created, cleaning up old  {"old": "/root/.lotus/kvlog/metadata/1632295088.log.cbor", "new": "1632295370.log.cbor"}
2021-09-22T15:22:50.789+0800    ^[[34mINFO^[[0m backupds        backupds/log.go:230     new log head    {"loghead": "1632295370.log.cbor;44843098-3914-4ef0-8e4e-6d845d35958a;1632295370"}
2021-09-22T15:22:51.004+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/levels.go:183      All 27 tables opened in 198ms

2021-09-22T15:22:51.005+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/value.go:1158      Replaying file id: 26 at offset: 723367610

2021-09-22T15:22:51.005+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/value.go:1178      Replay took: 3.439µs

2021-09-22T15:22:51.022+0800    ^[[34mINFO^[[0m p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/127.0.0.1/tcp/44781 /ip4/192.168.2.129/tcp/44781 /ip4/172.20.0.1/tcp/44781 /ip4/172.19.0.1/tcp/44781 /ip4/172.17.0.1/tcp/44781 /ip4/172.22.0.1/tcp/44781 /ip6/::1/tcp/43507]
2021-09-22T15:22:51.227+0800    ^[[34mINFO^[[0m dt-impl impl/impl.go:182        start data-transfer module
2021-09-22T15:22:51.227+0800    ^[[34mINFO^[[0m dt-pushchanmon  pushchannelmonitor/pushchannelmonitor.go:134    Starting push channel monitor with 10 checks per 1m0s interval (check interval 6s); min bytes per interval: 1024, restart backoff: 10m0s; max consecutive restarts: 3
2021-09-22T15:22:51.229+0800    ^[[34mINFO^[[0m messagepool     messagepool/messagepool.go:404  mpool ready
2021-09-22T15:22:51.229+0800    ^[[34mINFO^[[0m markets loggers/loggers.go:38   module ready    {"module": "retrieval client"}
2021-09-22T15:22:51.237+0800    ^[[34mINFO^[[0m markets loggers/loggers.go:38   module ready    {"module": "client data transfer"}
2021-09-22T15:22:51.246+0800    ^[[34mINFO^[[0m markets loggers/loggers.go:38   module ready    {"module": "discovery"}
2021-09-22T15:22:51.254+0800    ^[[34mINFO^[[0m markets loggers/loggers.go:38   module ready    {"module": "storage client"}
2021-09-22T15:22:52.104+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/levels.go:1000     [Compactor: 0] Running compaction: {level:0 score:1 dropPrefixes:[]} for level: 0

2021-09-22T15:22:55.768+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/levels.go:962      LOG Compact 0->1, del 8 tables, add 6 tables, took 3.663721469s

2021-09-22T15:22:55.768+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/levels.go:1010     [Compactor: 0] Compaction for level: 0 DONE
2021-09-22T15:22:55.768+0800    ^[[34mINFO^[[0m badgerbs        v2@v2.2007.2/levels.go:1000     [Compactor: 0] Running compaction: {level:1 score:1.3315179832279682 dropPrefixes:[]} for level: 1

2021-09-22T15:22:56.223+0800    ^[[34mINFO^[[0m peermgr peermgr/peermgr.go:210  connecting to bootstrap peers
2021-09-22T15:22:56.998+0800    ^[[34mINFO^[[0m chain   chain/sync_manager.go:218       selected initial sync target: [bafy2bzacea2e5limaokewh5m3x7wvryxvslchubihgpapzub7momiosqdwzvu bafy2bzaceaqm6l2ks3h6aqeq6fsf64kdnbik5oegmhe5kn3zuwx5l72hldqi4 bafy2bzaceclbagvaihdmjfygg3i5c6endrocknamvpopww2ywnwi6gr7qpobk bafy2bzacebhiqbiqhiev7iybyachpfgfyzd3o2tt53rbgslkubjzmlieu4qh2 bafy2bzacedyt4ts73cg4rmctphatuziud7nm45xmn3rj4vlqjl7yu5rpoq7zy bafy2bzacead7jv6dizxfis7nbmbkrmrjpnyrentpov7jv4vvmrjhlv2p77amm bafy2bzacedzp3h4riqu35bumk765xe43qcwjteeujk3mgrniu4yrffbckevda bafy2bzaced4wkxpgembdtwxnnvp3l2fk7q66wmqh5wlwjxribqh43mo3r4ogc bafy2bzaceb7ubwxzkfjjcxqj24dn2dhvfo7ftf23pblonsmxlm737lqlie46y bafy2bzaceb7hkue62t2qgpz2yjgu5m7skbasnctjgzcq34bfp3v4bfjtzxt6i bafy2bzacea7trxjkuzicffaagfccr5s53tw5jsfovw3lhypw4rdarxmgeggw4]
2021-09-22T15:22:56.998+0800    ^[[34mINFO^[[0m chain   chain/sync_manager.go:314       worker 0 syncing in [bafy2bzacea2e5limaokewh5m3x7wvryxvslchubihgpapzub7momiosqdwzvu bafy2bzaceaqm6l2ks3h6aqeq6fsf64kdnbik5oegmhe5kn3zuwx5l72hldqi4 bafy2bzaceclbagvaihdmjfygg3i5c6endrocknamvpopww2ywnwi6gr7qpobk bafy2bzacebhiqbiqhiev7iybyachpfgfyzd3o2tt53rbgslkubjzmlieu4qh2 bafy2bzacedyt4ts73cg4rmctphatuziud7nm45xmn3rj4vlqjl7yu5rpoq7zy bafy2bzacead7jv6dizxfis7nbmbkrmrjpnyrentpov7jv4vvmrjhlv2p77amm bafy2bzacedzp3h4riqu35bumk765xe43qcwjteeujk3mgrniu4yrffbckevda bafy2bzaced4wkxpgembdtwxnnvp3l2fk7q66wmqh5wlwjxribqh43mo3r4ogc bafy2bzaceb7ubwxzkfjjcxqj24dn2dhvfo7ftf23pblonsmxlm737lqlie46y bafy2bzaceb7hkue62t2qgpz2yjgu5m7skbasnctjgzcq34bfp3v4bfjtzxt6i bafy2bzacea7trxjkuzicffaagfccr5s53tw5jsfovw3lhypw4rdarxmgeggw4]
2021-09-22T15:22:57.556+0800    ^[[34mINFO^[[0m chain   chain/sync.go:1360      Got blocks: 950804 500
2021-09-22T15:22:58.258+0800    ^[[34mINFO^[[0m chain   chain/sync.go:1360      Got blocks: 950295 500
SIGILL: illegal instruction
PC=0x2869903 m=10 sigcode=2
instruction bytes: 0x41 0xf 0x38 0xcb 0xd5 0xc5 0xf9 0x70 0xc0 0xe 0xc5 0x79 0x7f 0xe9 0xf 0x38

goroutine 0 [idle]:
runtime: unknown pc 0x2869903
stack: frame={sp:0x7f5a80a07158, fp:0x0} stack=[0x7f5a8020bec8,0x7f5a80a0bac8)
00007f5a80a07058:  0000000000000000  00007f5a54000020
00007f5a80a07068:  00007f5a80a070c8  0000000004607860
00007f5a80a07078:  0000002000000000  00007f5a80a07103
00007f5a80a07088:  0000000000000098  00007f5a80a073c8
00007f5a80a07098:  00007f5a80a0a870  00007f5a80a07290
00007f5a80a070a8:  00007f5a80a07160  00007f5a80a073b0
00007f5a80a070b8:  000000000250b6ba  00007f51fce211d0
00007f5a80a070c8:  00007f5a80a07290  000000000462b0c0
00007f5a80a070d8:  0000000000000004  0000000000000000
00007f5a80a070e8:  00007f51fce19c60  00007f5a80a07130
00007f5a80a070f8:  0000000000000003  0000000000000000
00007f5a80a07108:  0000000000000000  0000000000000000
00007f5a80a07118:  0000000000000000  0000000000000000
00007f5a80a07128:  0000000000000000  0000000000000000
00007f5a80a07138:  0000000000000000  0000000000000000
00007f5a80a07148:  0000000000000000  bb67ae856a09e667
00007f5a80a07158: <000000000230d484  00007f5a80a072f8
00007f5a80a07168:  00007f51fce21320  00007f5a80a073c8
00007f5a80a07178:  00007f5a80a0a870  00007f5a80a073c8
00007f5a80a07188:  0000000000000000  00007f5a80a073b0
00007f5a80a07198:  0000000002803a19  00007f51fce21320
00007f5a80a071a8:  0000000000000098  000000000000005d
00007f5a80a071b8:  0000000000000001  0000000000000008
00007f5a80a071c8:  0000000000000000  0000000000000000
00007f5a80a071d8:  0000000000000000  00007f51fce190a0
00007f5a80a071e8:  0000000000000009  0000000000000009
00007f5a80a071f8:  00007f51fce19b10  0000000000000001
00007f5a80a07208:  0000000000000001  0000000000000008
00007f5a80a07218:  0000000000000000  0000000000000000
00007f5a80a07228:  00007f51fce190a0  0000000000000009
00007f5a80a07238:  0000000000000009  00007f51fce19b10
00007f5a80a07248:  0000000000000001  0000000000000001
runtime: unknown pc 0x2869903
stack: frame={sp:0x7f5a80a07158, fp:0x0} stack=[0x7f5a8020bec8,0x7f5a80a0bac8)
00007f5a80a07058:  0000000000000000  00007f5a54000020
00007f5a80a07068:  00007f5a80a070c8  0000000004607860
00007f5a80a07078:  0000002000000000  00007f5a80a07103
00007f5a80a07088:  0000000000000098  00007f5a80a073c8
00007f5a80a07098:  00007f5a80a0a870  00007f5a80a07290
00007f5a80a070a8:  00007f5a80a07160  00007f5a80a073b0
00007f5a80a070b8:  000000000250b6ba  00007f51fce211d0
00007f5a80a070c8:  00007f5a80a07290  000000000462b0c0
00007f5a80a070d8:  0000000000000004  0000000000000000
00007f5a80a070e8:  00007f51fce19c60  00007f5a80a07130
00007f5a80a070f8:  0000000000000003  0000000000000000
00007f5a80a07108:  0000000000000000  0000000000000000
00007f5a80a07118:  0000000000000000  0000000000000000
00007f5a80a07128:  0000000000000000  0000000000000000
00007f5a80a07138:  0000000000000000  0000000000000000
00007f5a80a07148:  0000000000000000  bb67ae856a09e667
00007f5a80a07158: <000000000230d484  00007f5a80a072f8
00007f5a80a07168:  00007f51fce21320  00007f5a80a073c8
00007f5a80a07178:  00007f5a80a0a870  00007f5a80a073c8
00007f5a80a07188:  0000000000000000  00007f5a80a073b0
00007f5a80a07198:  0000000002803a19  00007f51fce21320
00007f5a80a071a8:  0000000000000098  000000000000005d
00007f5a80a071b8:  0000000000000001  0000000000000008
00007f5a80a071c8:  0000000000000000  0000000000000000
00007f5a80a071d8:  0000000000000000  00007f51fce190a0
00007f5a80a071e8:  0000000000000009  0000000000000009
00007f5a80a071f8:  00007f51fce19b10  0000000000000001
00007f5a80a07208:  0000000000000001  0000000000000008
00007f5a80a07218:  0000000000000000  0000000000000000
00007f5a80a07228:  00007f51fce190a0  0000000000000009
00007f5a80a07238:  0000000000000009  00007f51fce19b10
00007f5a80a07248:  0000000000000001  0000000000000001

goroutine 1887 [syscall]:
runtime.cgocall(0x1aa3e20, 0xc01b279210, 0x29ca140)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc01b2791b8 sp=0xc01b279180 pc=0x52e4db
github.com/filecoin-project/filecoin-ffi/generated._Cfunc_fil_verify_window_post(0xb2505a49ef5f964f, 0x709fa3df1fbcbf02, 0xdd4430dad58781bc, 0x1ccb34c6a2ebc8c, 0x7f5a54004f30, 0x125a, 0x7f5a540856a0, 0x1, 0x14bd, 0x0, ...)
        _cgo_gotypes.go:1917 +0x4c fp=0xc01b279210 sp=0xc01b2791b8 pc=0x10cb14c
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyWindowPost.func1(0xb2505a49ef5f964f, 0x709fa3df1fbcbf02, 0xdd4430dad58781bc, 0x1ccb34c6a2ebc8c, 0x7f5a54004f30, 0x125a, 0x7f5a540856a0, 0x1, 0x14bd, 0x0, ...)
        /home/ps/src/mainnet/extern/filecoin-ffi/generated/generated.go:795 +0xf4 fp=0xc01b2792c8 sp=0xc01b279210 pc=0x10d9b94
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyWindowPost(0xb2505a49ef5f964f, 0x709fa3df1fbcbf02, 0xdd4430dad58781bc, 0x1ccb34c6a2ebc8c, 0x0, 0x0, 0x0, 0xc01ffa6000, 0x125a, 0x125a, ...)
        /home/ps/src/mainnet/extern/filecoin-ffi/generated/generated.go:795 +0x238 fp=0xc01b2793e8 sp=0xc01b2792c8 pc=0x10d8658
github.com/filecoin-project/filecoin-ffi.VerifyWindowPoSt(0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, 0x1, 0xc01ff80000, 0x125a, 0x125a, 0xa3d, ...)
        /home/ps/src/mainnet/extern/filecoin-ffi/proofs.go:117 +0x36d fp=0xc01b2795e0 sp=0xc01b2793e8 pc=0x10ded8d
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.proofVerifier.VerifyWindowPoSt(0x32a8950, 0xc000044088, 0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, 0x1, 0xc01ff80000, 0x125a, ...)
        /home/ps/src/mainnet/extern/sector-storage/ffiwrapper/verifier_cgo.go:131 +0x118 fp=0xc01b279670 sp=0xc01b2795e0 pc=0x10f2018
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*proofVerifier).VerifyWindowPoSt(0x47f59a8, 0x32a8950, 0xc000044088, 0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, 0x1, 0xc01ff80000, ...)
        <autogenerated>:1 +0x78 fp=0xc01b2796f8 sp=0xc01b279670 pc=0x10f4338
github.com/filecoin-project/lotus/chain/vm.(*syscallShim).VerifyPoSt(0xc01f72d7a0, 0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, 0x1, 0xc01ff80000, 0x125a, 0x125a, ...)
        /home/ps/src/mainnet/chain/vm/syscalls.go:242 +0x82 fp=0xc01b279788 sp=0xc01b2796f8 pc=0x1246a62
github.com/filecoin-project/lotus/chain/vm.pricedSyscalls.VerifyPoSt(0x32b98e8, 0xc01f72d7a0, 0x32c8aa0, 0xc0001a2300, 0xc01f756eb8, 0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, ...)
        /home/ps/src/mainnet/chain/vm/gas.go:255 +0x1ba fp=0xc01b2798c0 sp=0xc01b279788 pc=0x123b8da
github.com/filecoin-project/lotus/chain/vm.(*pricedSyscalls).VerifyPoSt(0xc01f76e060, 0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, 0x1, 0xc01ff80000, 0x125a, 0x125a, ...)
        <autogenerated>:1 +0xbb fp=0xc01b279980 sp=0xc01b2798c0 pc=0x1253b1b
github.com/filecoin-project/lotus/chain/vm.(*Runtime).VerifyPoSt(0xc019144d80, 0xc01f4f8e60, 0x20, 0x20, 0xc01f75f800, 0x1, 0x1, 0xc01ff80000, 0x125a, 0x125a, ...)
        <autogenerated>:1 +0x5d fp=0xc01b2799f8 sp=0xc01b279980 pc=0x1252dbd
github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.verifyWindowedPost(0x32d5d78, 0xc019144d80, 0xe7527, 0xc01f78e000, 0x125a, 0x125a, 0xc01f75f800, 0x1, 0x1)
        /home/ps/go/pkg/mod/github.com/filestar-project/specs-actors/v2@v2.1.1/actors/builtin/miner/miner_actor.go:2082 +0x375 fp=0xc01b279b60 sp=0xc01b2799f8 pc=0xd81fd5
github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.Actor.SubmitWindowedPoSt.func1()
        /home/ps/go/pkg/mod/github.com/filestar-project/specs-actors/v2@v2.1.1/actors/builtin/miner/miner_actor.go:484 +0x9ea fp=0xc01b279d90 sp=0xc01b279b60 pc=0xda898a
github.com/filecoin-project/lotus/chain/vm.(*Runtime).StateTransaction(0xc019144d80, 0x32911a8, 0xc0007e9110, 0xc01f4c0780)
        /home/ps/src/mainnet/chain/vm/runtime.go:441 +0x154 fp=0xc01b279e00 sp=0xc01b279d90 pc=0x1244414
github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.Actor.SubmitWindowedPoSt(0x32d5d78, 0xc019144d80, 0xc01f72d980, 0x0)
        /home/ps/go/pkg/mod/github.com/filestar-project/specs-actors/v2@v2.1.1/actors/builtin/miner/miner_actor.go:388 +0x1fc fp=0xc01b279eb8 sp=0xc01b279e00 pc=0xd7915c
github.com/filecoin-project/specs-actors/v2/actors/builtin/miner.Actor.SubmitWindowedPoSt-fm(0x32d5d78, 0xc019144d80, 0xc01f72d980, 0x0)
        /home/ps/go/pkg/mod/github.com/filestar-project/specs-actors/v2@v2.1.1/actors/builtin/miner/miner_actor.go:370 +0x48 fp=0xc01b279ee8 sp=0xc01b279eb8 pc=0xdb5b68
runtime.call32(0xc01f76ec90, 0xc01b20b140, 0xc01f75f840, 0x1800000020)
        /usr/local/go/src/runtime/asm_amd64.s:551 +0x3e fp=0xc01b279f18 sp=0xc01b279ee8 pc=0x59be7e
reflect.Value.call(0x2aa6580, 0xc01b20b140, 0x13, 0x2e00bed, 0x4, 0xc01b27a1f8, 0x2, 0x2, 0x326e6c0, 0xc01f76eba0, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8e7 fp=0xc01b27a120 sp=0xc01b279f18 pc=0x5f1467
reflect.Value.Call(0x2aa6580, 0xc01b20b140, 0x13, 0xc01b27a1f8, 0x2, 0x2, 0x7f5a8003e258, 0xc01f4f8d40, 0xc01f76eba0)
        /usr/local/go/src/reflect/value.go:337 +0xb9 fp=0xc01b27a1a0 sp=0xc01b27a120 pc=0x5f0939
```

**Comment by codefather-filestar** [comment]
are you running on a AMD-cpu server ?
